### ISSUE TITLE
Links and Buttons are not  inheriting the correct styles from Customizer options

### ISSUE THREAD

**Issue by joseabreu1985** [lightspeeddevelopment/lsx-customizer#34]
### Describe the bug
Links and Buttons are not inheriting the correct styles from Customizer options for some extensions like Events Calendar.
This s also happening on the blog.

### Steps to Reproduce
1. Go to the Customizer options
2. Click on Colors
3. Change a few colors around, specially primary color and the body link color.
4. See front, pages like event calendar archive and blog archive are not following these new colors.

### Expected behavior
At least the buttons and links should take the customizer colors.

### Environment information
 - Device: all
 - OS: all
 - Browser and version: all
 - WordPress version: 5.5

**Comment by viscosho** [comment]
Fixed in this commit https://github.com/lightspeeddevelopment/lsx-customizer/commit/3abeff0c47361f97aab9dd35d5fd719dc2535a2e
